project:
  type: website

website:
  title: "samiksha_portfolio"
  # navbar:
  #   right:
  #     - href: index.qmd
  #       text: Home
      #- about.qmd
resources: 
    - "*.html"
    - "*.js"
    - "*.css"
    
format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

